# Este archivo sirve para crear registros de prueba
Task.create(tarea: "Sacar al perro")
Task.create(tarea: "Lavar la ropa")
Task.create(tarea: "Tomar mi medicina")
Task.create(tarea: "Estudiar Active Record")
Task.create(tarea: "Leer")
Task.create(tarea: "Estudiar Java")
Task.create(tarea: "Terminar el template")
Task.create(tarea: "Tender la cama")
Task.create(tarea: "Proceso de titulacion")
